planning_node:
  ros__parameters:
    # Map (should match sim.yaml)
    map_path: 'photo_track'
    map_img_ext: '.png'
    waypoint_spacing: 0.2
    vehicle_width: 0.31

    # Spawn pose (should match sim.yaml)
    sx: 4.023
    sy: 4.938
    stheta: -1.5708

    # Velocity planner
    v_max: 10.0
    v_min: 1.5
    a_lat_max: 6.0
    a_lon_max: 6.0
    xte_threshold: 0.15
    k_xte: 0.8

    # Planning loop
    planning_frequency: 20.0
