controls_node:
  ros__parameters:
    # Vehicle
    wheelbase: 0.3302

    # Pure pursuit
    lookahead_gain: 0.5
    min_lookahead: 0.5
    max_lookahead: 3.0

    # Limits
    max_steering_angle: 0.4189
    max_speed: 10.0

    # Control loop
    control_frequency: 50.0
